### PR TITLE
Added tests for helpers

### PR DESCRIPTION
**Pull request by aumarbello**
Want to know if this is inline with the kind of tests expected.

### CODE REVIEW

**Comment by Zhuinden** [comment]
Technically a good start, way better than what I had!

----

However, for complete unit tests, in order to test both happy and "unhappy" paths, each `check` should have a failure path test associated with it. For example,

``` kotlin
    @Test
    fun hasEmptyTextSuccess() {
        R.id.tv_empty_text_view.checkHasEmptyText()
        // OK!
    }

    @Test
    fun hasEmptyTextFailureThrowsAssertion() {
        try {
            R.id.tv_not_empty_text_view.checkHasEmptyText()
            Assert.fail("should have failed")
        } catch(e: AssertionError) {
            assertThat(e.message).isNotEqualTo("should have failed")
            // OK!
        }
    }
``` 

for the `assertThat`, I added

    androidTestImplementation 'org.assertj:assertj-core:3.9.1'

And

    import org.junit.Assert
    import org.assertj.core.api.Java6Assertions.*

Also as the tests are Kotlin, you can lucky move this whole "should have failed" thing into its own inline function.

    inline fun verifyAssertion(assertion: () -> Unit) {
        try {
            assertion()
            Assert.fail("should have failed")
        } catch(e: AssertionError) {
            assertThat(e.message).isNotEqualTo("should have failed")
            // OK!
        }
    }

Then

           verifyAssertion { R.id.tv_not_empty_text_view.checkHasEmptyText() }

-----

So for happy path it's good, but complete coverage should cover what exceptions are expected, too. Otherwise you can't guarantee that you get the expected assertion error when you actually provide the wrong thing 😉 

Thanks for the help, by the way! 🙂

**Comment by aumarbello** [comment]
I wanted to also test for sad paths but couldn't figure out how to do so, thanks for pointing it out.

I will write the corresponding tests and push.

**Review by Zhuinden — APPROVED** [review]
Awesome! 👍 

Thank you for the contribution

**Comment by Zhuinden** [comment]
You know, I don't know if you have the authority to merge things.

If you don't, then I'll merge it, ok?

**Comment by aumarbello** [comment]
> You know, I don't know if you have the authority to merge things.
> 
> If you don't, then I'll merge it, ok?

I don't but I wanna add more tests before merging, will push more commits to this PR.

**Comment by Zhuinden** [comment]
Okay! :slightly_smiling_face:

**Comment by aumarbello** [comment]
> Okay!

Done, please review and consider merging.

**Pull request merged**
